### ISSUE TITLE
fetch is not defined 是不是node版本问题？

### ISSUE THREAD

**Issue by pengchenggang** [bosichong/Link-Validator#1]
fetch is not defined 是不是node版本问题？
![image](https://user-images.githubusercontent.com/7833742/236718726-551474de-281c-4600-b6a2-9a9ace0602d2.png)

**Comment by pengchenggang** [comment]
补充下，我用的vscode，我看你那是idea，我这只能开一个idea，已被主项目占用了，只能用vscode开别的。

**Comment by bosichong** [comment]
fetch()  需要 node 18+的环境。

**Comment by pengchenggang** [comment]
已解决，升级了18的环境，好久没升级过了，嘿嘿~~
![image](https://user-images.githubusercontent.com/7833742/236720611-f9785f11-5e69-493c-a090-49ce060ffb02.png)
